somelocation.ru,2026:
  tag.*: "https://github.com/dont-you/dereferencer/blob/master/src/integration-test/resources/test-schemes/schemes/urn-resolving/file1.json"
  tag.with.maxprefix*: "https://github.com/dont-you/dereferencer/blob/feature-urn-tag-resolving/src/integration-test/resources/test-schemes/schemes/urn-resolving/target.json"
